### ISSUE TITLE
error forwarding

### ISSUE THREAD

**Issue by thejoshwolfe** [tiehuis/zig-bn#1]
`Bn.init()` currently calls `%%limbs.append(0);`. instead it should `%return limbs.append(0);` so that clients can handle out of memory situations. similarly with other​ `%%` prefix operators.

in general, a library should never `%%` prefix another library's errors.

**Comment by tiehuis** [comment]
You are right.

Wasn't 100% on how I was going to handle memory allocation errors when I started since I wasn't sure the noise they would result in. GMP notably doesn't really provide a good way of handling oom issues.

However, the `%%` operator in zig on the caller side to emulate the same behavior is pretty minimal so I don't think the added line noise is much of an issue.

Thanks.
